In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow.keras as keras
import json
import os
from zipfile import ZipFile

In [2]:
print(tf.config.list_physical_devices('GPU'))
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

print(tf.test.is_built_with_cuda())
print(tf.config.list_physical_devices('GPU'))

[]
Num GPUs Available:  0
True
[]


In [3]:
!pip install kaggle

In [4]:
kaggle_credentials = json.load(open("kaggle.json"))

In [5]:
#kaggle API credentials
os.environ['KAGGLE_USERNAME'] = kaggle_credentials["username"]
os.environ['KAGGLE_KEY'] = kaggle_credentials["key"]

In [ ]:
#downloads dataset from kaggle
!kaggle datasets download -d vipoooool/new-plant-diseases-dataset

In [6]:
#unzip dataset
with ZipFile("new-plant-diseases-dataset.zip", 'r') as zip_ref:
    zip_ref.extractall()

<H4>Data Preprocessing
<H5> Training set preprocessing

In [7]:
training_set = keras.utils.image_dataset_from_directory(
    'New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 70295 files belonging to 38 classes.


<H4> Validation set processing 

In [8]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[113. 108. 112.]
   [126. 121. 125.]
   [128. 123. 127.]
   ...
   [162. 156. 158.]
   [165. 159. 161.]
   [174. 168. 170.]]

  [[118. 113. 117.]
   [123. 118. 122.]
   [124. 119. 123.]
   ...
   [169. 163. 165.]
   [172. 166. 168.]
   [179. 173. 175.]]

  [[115. 110. 114.]
   [119. 114. 118.]
   [126. 121. 125.]
   ...
   [169. 163. 165.]
   [174. 168. 170.]
   [178. 172. 174.]]

  ...

  [[ 87.  81.  85.]
   [ 85.  79.  83.]
   [ 84.  78.  82.]
   ...
   [108. 100.  98.]
   [105.  97.  95.]
   [ 96.  88.  86.]]

  [[ 86.  80.  84.]
   [ 87.  81.  85.]
   [ 87.  81.  85.]
   ...
   [112. 104. 102.]
   [110. 102. 100.]
   [102.  94.  92.]]

  [[ 82.  76.  80.]
   [ 87.  81.  85.]
   [ 92.  86.  90.]
   ...
   [101.  93.  91.]
   [110. 102. 100.]
   [115. 107. 105.]]]


 [[[113. 101. 111.]
   [119. 107. 117.]
   [124. 112. 122.]
   ...
   [136. 124. 134.]
   [139. 127. 137.]
   [143. 131. 141.]]

  [[107.  95. 105.]
   [110.  98. 108.]
   [114. 102. 112.]
   ...
   [135. 1

In [9]:
validation_set = keras.utils.image_dataset_from_directory(
    'New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 17572 files belonging to 38 classes.


<h4> Building convolutional neural network

In [10]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
from tensorflow.keras.models import Sequential

In [11]:
#definition of the model
model = Sequential()

model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation = 'relu', input_shape=[256, 256, 3]))
model.add(Conv2D(32, (3, 3), activation = 'relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation = 'relu'))
model.add(Conv2D(64,(3, 3), activation='relu'))
model.add(MaxPool2D(2, 2))

model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation = 'relu'))
model.add(Conv2D(128,(3, 3), activation='relu'))
model.add(MaxPool2D(2, 2))

model.add(Conv2D(filters=256, kernel_size=3, padding='same',activation = 'relu'))
model.add(Conv2D(256,(3, 3), activation='relu'))
model.add(MaxPool2D(2, 2))

model.add(Conv2D(filters=512, kernel_size=3, activation = 'relu'))
model.add(Conv2D(512,(3, 3), activation='relu'))
model.add(MaxPool2D(2, 2))

model.add(Dropout(0.25))

#flattens to one dimension array for the output layers
model.add(Flatten())
model.add(Dense(units=1500, activation='relu'))

model.add(Dropout(0.4))

#output layer
model.add(Dense(units=38, activation='softmax'))

<h4> Compile model

In [12]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 256, 256, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 254, 254, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 127, 127, 32)     0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 127, 127, 64)      18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 125, 125, 64)      36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 62, 62, 64)       0         
 2D)                                                    

<H4> Model training

In [ ]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=5)

Epoch 1/5
   1/2197 [..............................] - ETA: 1:59:23 - loss: 6.3599 - accuracy: 0.0000e+00

<H4> Model evaluation

In [ ]:
train_loss, train_accuracy = model.evaluate(training_set)

In [ ]:
print(train_loss, train_accuracy)

In [ ]:
validation_loss, validation_accuracy = model.evaluate(validation_set)

In [ ]:
print(validation_loss, validation_accuracy)

<H4> Save model

In [ ]:
from keras import Model

model.save(filepath="trained_model/trained_disease_detection.keras", overwrite=True, save_format="keras")

In [ ]:
training_history.history

<h5> Recording history in JSON

In [ ]:
import json
with open("training_history.json", "w") as f:
    json.dump(training_history.history, f)

<H4> Visualizations and Metrics

In [ ]:
epochs = [i for i in range(1,6)]
plt.plot(epochs, training_history.history['accuracy'], color='green', label="training accuracy")
plt.plot(epochs, training_history.history['val_accuracy'], color='red', label="validation accuracy")
plt.xlabel("Number of epochs")
plt.ylabel("Accuracy")
plt.title("Accuracy per Epoch")
plt.legend()
plt.show()

In [ ]:
class_name = validation_set.class_names
class_name

In [ ]:
test_set = keras.utils.image_dataset_from_directory(
    'Plant_Diseases_Dataset/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
) 

In [ ]:
y_pred = model.predict(test_set)
y_pred

In [ ]:
predicted_cats = tf.argmax(y_pred, axis=1)

In [ ]:
true_cats = tf.concat([y for x,y in test_set], axis=0)
true_cats

In [ ]:
Y_true = tf.argmax(true_cats, axis=1)
Y_true

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix


In [ ]:
print(classification_report(Y_true, predicted_cats, target_names=class_name))

In [ ]:
cm = confusion_matrix(Y_true, predicted_cats)
cm

In [ ]:
from IPython.core.pylabtools import figsize

plt.figure(figsize(40,40))
sns.heatmap(cm, annot=True, annot_kws={'size':10})
plt.xlabel("predicted class", fontsize=20)
plt.ylabel("true class", fontsize=20)
plt.title("Plant Disease Confusion Matrix", fontsize=25)
plt.show()